# Generated by Django 5.2.6 on 2025-11-20 12:29

import django.db.models.deletion
import report_issue.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('initial', 'Initial Report'), ('follow_up', 'Follow Up'), ('escalation', 'Escalation'), ('reminder', 'Reminder'), ('final_notice', 'Final Notice')], max_length=20)),
                ('subject_template', models.CharField(max_length=300)),
                ('body_template', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='CSS class or icon name', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Issue Categories',
            },
        ),
        migrations.CreateModel(
            name='IssueTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title_template', models.CharField(max_length=200)),
                ('description_template', models.TextField()),
                ('suggested_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10)),
                ('is_safety_issue', models.BooleanField(default=False)),
                ('affects_habitability', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_issue.issuecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='draft', max_length=20)),
                ('location', models.CharField(help_text='e.g., Kitchen, Bathroom, Living Room', max_length=200)),
                ('landlord_email', models.EmailField(blank=True, help_text="Landlord's email address", max_length=254)),
                ('property_manager_email', models.EmailField(blank=True, help_text="Property manager's email address", max_length=254)),
                ('contact_preference', models.CharField(choices=[('landlord', 'Contact Landlord'), ('property_manager', 'Contact Property Manager')], default='landlord', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, help_text='Expected resolution date', null=True)),
                ('escalation_level', models.IntegerField(default=0, help_text='0=Normal, 1=First escalation, 2=Second escalation, etc.')),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_safety_issue', models.BooleanField(default=False)),
                ('affects_habitability', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_issue.issuecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('status_change', 'Status Change'), ('landlord_response', 'Landlord Response'), ('user_note', 'User Note'), ('escalation', 'Escalation'), ('resolution', 'Resolution')], max_length=20)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='report_issue.propertyissue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=report_issue.models.issue_photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='report_issue.propertyissue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('initial', 'Initial Report'), ('follow_up', 'Follow Up'), ('escalation', 'Escalation'), ('reminder', 'Reminder'), ('final_notice', 'Final Notice')], max_length=20)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='report_issue.propertyissue')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
