# Generated by Django 5.2.8 on 2025-11-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_user_house_flat_number'),
        ('report_issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyissue',
            name='created_from_compliance',
            field=models.BooleanField(default=False, help_text='Issue created from landlord compliance assessment'),
        ),
        migrations.AlterField(
            model_name='issueemail',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.user'),
        ),
        migrations.AlterField(
            model_name='issueupdate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.user'),
        ),
        migrations.AlterField(
            model_name='propertyissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_issues', to='application.user'),
        ),
    ]
