# Generated by Django 5.2.8 on 2025-11-18 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0006_remove_user_marketing_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('flat', 'Flat/Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room'), ('maisonette', 'Maisonette'), ('bungalow', 'Bungalow')], max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('weekly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furnished', models.CharField(blank=True, max_length=50)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('rightmove', 'Rightmove'), ('openrent', 'OpenRent'), ('spareroom', 'SpareRoom'), ('zoopla', 'Zoopla')], max_length=50)),
                ('source_url', models.URLField()),
                ('source_id', models.CharField(max_length=200)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('main_image_url', models.URLField(blank=True)),
                ('images_data', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_duplicate', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'unique_together': {('source', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_type', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('search_area', models.CharField(max_length=200)),
                ('search_radius_miles', models.FloatField(default=2.0)),
                ('average_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('median_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_properties_found', models.IntegerField(default=0)),
                ('rent_percentile', models.FloatField(blank=True, null=True)),
                ('market_summary', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
                ('comparable_properties', models.ManyToManyField(to='market_analysis.propertylisting')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('property_type', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('max_radius', models.FloatField(default=2.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('properties_scraped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
        ),
    ]
