# Generated by Django 5.2.6 on 2025-11-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0006_remove_user_marketing_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(help_text='Full property address', max_length=300)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('bedrooms', models.CharField(blank=True, max_length=50)),
                ('landlord_name', models.CharField(blank=True, max_length=200)),
                ('landlord_type', models.CharField(choices=[('landlord', 'Direct Landlord'), ('agent', 'Property Agent'), ('unknown', 'Unknown')], default='unknown', max_length=100)),
                ('overall_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 star rating')),
                ('title', models.CharField(help_text='Brief title for your review', max_length=200)),
                ('review_text', models.TextField(help_text='Detailed review content')),
                ('property_condition_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('landlord_communication_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('value_for_money_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('maintenance_response_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('rent_amount', models.CharField(blank=True, help_text='Weekly/Monthly rent', max_length=100)),
                ('tenancy_duration', models.CharField(blank=True, max_length=100)),
                ('would_recommend', models.BooleanField(default=True)),
                ('issues_reported', models.TextField(blank=True, help_text='Any issues during tenancy')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('moderator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_reviews', to='application.user')),
            ],
            options={
                'verbose_name': 'Rent Review',
                'verbose_name_plural': 'Rent Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
