# Generated by Django 5.2.8 on 2025-11-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='rental_situation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
