# Generated by Django 5.2.8 on 2025-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_user_bathrooms_user_has_lounge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gdpr_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
