# Generated by Django 5.2.8 on 2025-11-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_user_gdpr_consent_user_marketing_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms_conditions',
        ),
        migrations.AddField(
            model_name='user',
            name='terms_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
