# Generated by Django 5.2.8 on 2025-11-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_user_privacy_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marketing_emails',
        ),
    ]
