# Generated by Django 5.2.8 on 2025-11-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_user_marketing_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_lounge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
