# Generated by Django 5.2.8 on 2025-11-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_user_bathrooms_alter_user_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='property_condition',
            field=models.IntegerField(blank=True, help_text='Property condition rating (1-10)', null=True),
        ),
    ]
