# Generated by Django 5.2.6 on 2025-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_user_property_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house_flat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
